title_short: ELM
title: Evan Lori Mahone
description: "Evan Lori Mahone's website."
url: "http://evanlori.com"

fullname: Evan Lori Mahone
location: "Baltimore, MD"

license: GPL3
license_link: "https://www.gnu.org/licenses/gpl-3.0-standalone.html"

# Build settings
cloud_name: "evanlori"
markdown: kramdown
plugins:
  - jekyll-paginate-v2

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - .vscode/
  - node_modules/
  - tasks/
  - populate_images.fish
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - Rakefile
  - yarn.lock

sass:
  style: expanded
  sass_dir: _sass

permalink: /portfolio/posts/:year/:month/:title.html

pagination:
  enabled: true
  per_page: 12
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2