title: Evan Lori Mahone
title_short: ELM
subtitle: "Artist. Programmer. Advocate."
location: "Baltimore, MD"
description: "Evan Lori Mahone's website."
url: "http://evanlori.com"
cloud_name: "evanlori"
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - .vscode/
  - node_modules/
  - tasks/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - Rakefile
  - yarn.lock

sass:
  style: expanded
  sass_dir: _sass

permalink: /portfolio/posts/:year/:month/:title.html

pagination:
  enabled: true
  per_page: 12
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2